### ISSUE TITLE
Error in UseMethod(inner_join)

### ISSUE THREAD

**Issue by justlebeau** [timelyportfolio/d3hiveR#1]
Was beginning to look at this package and ran the example code:

```
>  d3hive( ranHiveData( nx = 5, ne = 1000, ns = c(1,3,8) ) )
>  Error in UseMethod("inner_join") : 
>  no applicable method for 'inner_join' applied to an object of class "function"
```

Just gave it a brief look so please advise on the missing code if available.

**Comment by timelyportfolio** [comment]
Glad you are trying it.  Could you also copy and paste sessioninfo as I cannot immediately see anything wrong? Particularly, what version of `dplyr` are you using?  Also, do you have `magrittr` installed?

**Comment by justlebeau** [comment]
Yes, magrittr is installed.

> sessionInfo(package="dplyr")
> R version 3.1.3 (2015-03-09)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> 
> locale:
> [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252  
> [3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C  
> [5] LC_TIME=English_United States.1252  
> attached base packages:
> character(0)
> other attached packages:
> [1] dplyr_0.3.0.2
> loaded via a namespace (and not attached):
>  [1] base_3.1.2      data.tree_0.1.7 datasets_3.1.2  graphics_3.1.2  grDevices_3.1.2
>  [6] grid_3.1.2      lattice_0.20-29 methods_3.1.2   plyr_1.8.1      R6_2.0  
> [11] rCharts_0.4.5   Rcpp_0.11.3     RJSONIO_1.3-0   stats_3.1.2     tools_3.1.2  
> [16] utils_3.1.2     whisker_0.3-2   yaml_2.1.13 
> R version 3.1.3 (2015-03-09)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> locale:
> [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252  
> [3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C  
> [5] LC_TIME=English_United States.1252  
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base  
> loaded via a namespace (and not attached):
>  [1] data.tree_0.1.7 grid_3.1.2      lattice_0.20-29 plyr_1.8.1      R6_2.0  
>  [6] rCharts_0.4.5   Rcpp_0.11.3     RJSONIO_1.3-0   tools_3.1.2     whisker_0.3-2  
> [11] yaml_2.1.13

**Comment by timelyportfolio** [comment]
If possible, could you start a clean R session and just do since I don't see much of the expected information from your `sessionInfo()` above?

```
library(HiveR)
library(d3hiveR)

sessionInfo()
```

On my Window 7 machine, I get

```
R version 3.1.2 (2014-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] HiveR_0.2-27 d3hiveR_0.1 

loaded via a namespace (and not attached):
 [1] assertthat_0.1     DBI_0.3.1          digest_0.6.4       dplyr_0.4.1        grid_3.1.2        
 [6] htmltools_0.2.8    htmlwidgets_0.5.1  jpeg_0.1-8         magrittr_1.5       parallel_3.1.2    
[11] plyr_1.8.1         png_0.1-7          RColorBrewer_1.1-2 Rcpp_0.11.5        tcltk_3.1.2       
[16] tkrgl_0.7          tools_3.1.2      
```

Then, after that, could you see if this works?

```
ranHiveData(nx=3)
```

Thanks, this should help determine the source of the problem.

**Comment by justlebeau** [comment]
Thanks for your help

```
> library(HiveR)
> library(d3hiveR)
> 
> sessionInfo()
R version 3.1.3 (2015-03-09)
Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] d3hiveR_0.1  HiveR_0.2-28

loaded via a namespace (and not attached):
 [1] assertthat_0.1     data.tree_0.1.7    DBI_0.3.1          digest_0.6.4       dplyr_0.4.2       
 [6] grid_3.1.2         htmltools_0.2.6    htmlwidgets_0.5    jpeg_0.1-8         lattice_0.20-29   
[11] magrittr_1.0.1     parallel_3.1.2     plyr_1.8.1         png_0.1-7          R6_2.0            
[16] rCharts_0.4.5      RColorBrewer_1.0-5 Rcpp_0.11.6        rgl_0.95.1247      RJSONIO_1.3-0     
[21] tcltk_3.1.2        tkrgl_0.7          tools_3.1.2        whisker_0.3-2      xtable_1.7-4      
[26] yaml_2.1.13
```

R version seems different a looks like several package updates are needed?

```
> ranHiveData(nx=3)
$nodes
 id   lab axis radius size   color
3   3 pgrem    3     10  1.5 #E41A1C
4   4 bwpbu    1     14  1.0 #E41A1C
6   6 eoyjh    1     61  1.0 #FF7F00
7   7 amliy    1     31  1.0 #377EB8
8   8 epdgi    2     24  0.5 #984EA3
9   9 awyui    3    100  0.5 #984EA3
12 12 bloeb    3      1  1.5 #984EA3
13 13 mdmch    3     71  0.5 #FF7F00
16 16 akaqy    1     85  1.0 #984EA3
17 17 mthbx    1     19  1.0 #4DAF4A
18 18 kdtib    2     74  1.5 #984EA3
19 19 btgyl    1     92  1.5 #FF7F00
20 20 lqruo    2     45  1.0 #E41A1C
21 21 lpfvu    2     29  1.0 #FF7F00
22 22 eytff    3     61  1.5 #377EB8
25 25 nlflm    2     33  1.5 #4DAF4A
26 26 uksoi    2     87  0.5 #FF7F00
28 28 wfcia    2      4  0.5 #984EA3
32 32 projg    3     94  0.5 #FF7F00
34 34 qdakn    2     24  0.5 #FF7F00
35 35 gxnlo    3      9  1.5 #FF7F00
37 37 qmhim    2     44  0.5 #984EA3
38 38 fuyin    2     69  1.0 #4DAF4A
39 39 bjixg    1      4  0.5 #984EA3
42 42 qhoii    3     81  1.5 #E41A1C
43 43 totso    1     55  1.0 #FF7F00

$edges
 id1 id2 weight   color
4   37  13      2 #377EB8
6   39  13      1 #E41A1C
8   20  17      3 #984EA3
11   4   3      1 #984EA3
13  42  26      2 #984EA3
14   9  17      2 #377EB8
15  13  25      2 #984EA3
16   3  26      1 #984EA3
17  21  19      1 #FF7F00
19  21   7      1 #4DAF4A
22  28  19      1 #377EB8
23  12  43      2 #377EB8
25  32  28      3 #4DAF4A
26  17  34      2 #E41A1C
27  22  18      3 #FF7F00
30  34  32      3 #377EB8
31  22  16      1 #984EA3
36   9  25      3 #4DAF4A
37   8  16      1 #4DAF4A
38  34  42      1 #FF7F00
40   6   9      1 #377EB8
41  13  17      2 #FF7F00
42  38  35      3 #984EA3
43  43  22      1 #4DAF4A

$type
[1] "2D"

$desc
[1] "3 axes -- 26 nodes -- 24 edges"

$axis.cols
[1] "#E41A1C" "#377EB8" "#4DAF4A"

attr(,"class")
[1] "HivePlotData"
```

**Comment by justlebeau** [comment]
It's the magrittr version...updated and plot runs.  Thanks for all the effort, truly appreciate it.

**Comment by timelyportfolio** [comment]
Great to hear, and I would love to see what you make with `d3hiveR`.  I'll add the higher version in the `magrittr` import to help make sure this doesn't happen to anyone else.
